### PR TITLE
This implementation is vulnerable to a replay attack

### PR DESCRIPTION
**Pull request by defrex**
Right now this pull request is just a failing test to get a conversation started.

The `nc` value in the header is supposed to be a counter to prevent replay attacks. Every time the same client and server nonce pair is used, the nonce counter must be incremented by the client. This will cause a new hash to be generated for the response. In this way, a request can never be replayed.

Solving this problem involves keeping track of client state on the server. A new model is probably the most straightforward solution, but it will balloon with a speed similar to Django's session table. Alternately it could be stored using Django's cache mechanism, but if the cache is lost there would have to be a forced expiry of all the server nonces, which would cause every client to 401 for a request.

What do you think?

### CODE REVIEW

**Comment by defrex** [comment]
@lraucy may as well get you in on this, since you seem to be working on this lib right now too.

**Comment by juanriaza** [comment]
Thanks @defrex for raising this issue.

I think that just relying on django's session engine is enough, so it would depend on which [session engine](https://docs.djangoproject.com/en/1.6/topics/http/sessions/#configuring-the-session-engine) is being used. A database-backed/cached session would fit perfectly, but a cookie-based one makes no sense for an API.

**Comment by defrex** [comment]
Hm, ya, that's an interesting approach. It hadn't occurred to me to use the session backend directly without requiring a session cookie to be set in the client.

This could end up being pretty unintuitive for anyone using this library though. What do you think about introducing a `DIGEST_ENGINE` setting that takes a session engine backend, where the default is the value of `SESSION_ENGINE`.

I'll start hacking on this shortly.

**Comment by juanriaza** [comment]
@defrex sounds good to me

**Comment by defrex** [comment]
Now that I've looked into this solution, it's at best in inelegant and confusing. Django's session backends are just not meant for anything other than sessions, and trying to change that is awkward.

I think the best way to go is to store it in the database, but add a simple `DIGESTAUTH_BACKEND` class to be an interface. That way it'll be simple for anyone to implement a cache backend, or whatever they want.

**Comment by juanriaza** [comment]
@defrex something like a base backend that defines how to implement a custom backend is a must. [`SessionBase`](https://github.com/django/django/blob/master/django/contrib/sessions/backends/base.py#L32) from django's session engine is a good starting point.

**Comment by defrex** [comment]
There we go. I'll add some docs soon, but reading `AbstractDigestBackend` should make things pretty clear.

**Comment by juanriaza** [comment]
@defrex travis is failing because of [importlib](http://stackoverflow.com/questions/9418064/conditionally-installing-importlib-on-python2-6) on python 2.6. Should be fixed at https://github.com/juanriaza/django-rest-framework-digestauth/commit/305f4fe0e1230bb0b0777c50cef60511db419ba5

**Comment by defrex** [comment]
Sweet, merged it in. Let's hope Travis comes back green this time.

**Comment by defrex** [comment]
facepalm

Travis doesn't use setup.py. So your solution works, but not for the CI server.

**Comment by juanriaza** [comment]
@defrex should be fixed at https://github.com/juanriaza/django-rest-framework-digestauth/commit/2b0edfa9c42c6ec7b27318cc67ebdeb0a7112c97

**Comment by defrex** [comment]
high five

**Comment by juanriaza** [comment]
:cake::star2::cake::star2::cake::bangbang:

**Pull request merged**
